project:
  type: website
  output-dir: docs

website:
  title: "Topy Workshop"
  twitter-card: true
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Outline
      - href: materials/activity/01-activity1/activity1.qmd
        text: "Activity 1"
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

